spring.application.name=instazoo

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=instazoo
spring.datasource.username=postgres
spring.datasource.password=

jwt.secret=dyWinPBMr302UZRO2iqE8AhNFrQCI+JKHi08rX+sEXf+6ePMOtGMmToPkQ8rcizdf0hcgILJUjbrKJIFrdGXOA==

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG